name: Pull Request Workflow

on:
  pull_request:
    branches:
      - '*'

jobs:
  validate_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven and run tests
        run: mvn -B clean verify